stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g npm@9

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy_app:
  stage: deploy
  script:
    - echo "Deploy step here (e.g., scp to server or Netlify/Vercel CLI)"
  only:
    - main
