module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "alert-500": "var(--alert-500)",
        bg: "var(--bg)",
        "bg-secondary": "var(--bg-secondary)",
        bgneutral: "var(--bgneutral)",
        bgwhite: "var(--bgwhite)",
        black: "var(--black)",
        "border-neutral": "var(--border-neutral)",
        "brand-light": "var(--brand-light)",
        brandmain: "var(--brandmain)",
        "carbon-darkest": "var(--carbon-darkest)",
        "carbon-neutral300": "var(--carbon-neutral300)",
        "content-link": "var(--content-link)",
        "content-muted": "var(--content-muted)",
        contentprimary: "var(--contentprimary)",
        contentsecondary: "var(--contentsecondary)",
        contenttertiary: "var(--contenttertiary)",
        errorprimary: "var(--errorprimary)",
        "foundation-greygrey-200": "var(--foundation-greygrey-200)",
        "foundation-greygrey-300": "var(--foundation-greygrey-300)",
        "foundationprimaryprimary-50": "var(--foundationprimaryprimary-50)",
        "foundationprimaryprimary-500": "var(--foundationprimaryprimary-500)",
        "gray-900": "var(--gray-900)",
        "grayscale-10": "var(--grayscale-10)",
        "grey-60": "var(--grey-60)",
        "grey-80": "var(--grey-80)",
        "grey-95": "var(--grey-95)",
        "input-color": "var(--input-color)",
        "label-colorlightprimary": "var(--label-colorlightprimary)",
        "labelsvibrant-tertiary": "var(--labelsvibrant-tertiary)",
        "m-3syslightbackground": "var(--m-3syslightbackground)",
        "m3syslighton-surface": "var(--m3syslighton-surface)",
        "neutralneutral-10": "var(--neutralneutral-10)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-400": "var(--primary-400)",
        "primary-50": "var(--primary-50)",
        "pure-white": "var(--pure-white)",
        "secondary-500": "var(--secondary-500)",
        "secondarycomp-primary-30": "var(--secondarycomp-primary-30)",
        "success-500": "var(--success-500)",
        "system-backgroundlightprimary": "var(--system-backgroundlightprimary)",
        "uigray-80": "var(--uigray-80)",
        warningprimary: "var(--warningprimary)",
        white: "var(--white)",
        "white-500": "var(--white-500)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-body-bold": "var(--body-body-bold-font-family)",
        "body-body-medium": "var(--body-body-medium-font-family)",
        "body-medium": "var(--body-medium-font-family)",
        "body-regular": "var(--body-regular-font-family)",
        "bold-22-px": "var(--bold-22-px-font-family)",
        "callout-medium": "var(--callout-medium-font-family)",
        "caption-caption-1-medium":
          "var(--caption-caption-1-medium-font-family)",
        "caption-caption-1-reguler":
          "var(--caption-caption-1-reguler-font-family)",
        "chart-text": "var(--chart-text-font-family)",
        "default-regular-callout": "var(--default-regular-callout-font-family)",
        "default-regular-title2": "var(--default-regular-title2-font-family)",
        "footnote-medium": "var(--footnote-medium-font-family)",
        "headline-bold": "var(--headline-bold-font-family)",
        "medium-12-px": "var(--medium-12-px-font-family)",
        "medium-13-px": "var(--medium-13-px-font-family)",
        "medium-14-px": "var(--medium-14-px-font-family)",
        "nunito-base-bold": "var(--nunito-base-bold-font-family)",
        "nunito-base-medium": "var(--nunito-base-medium-font-family)",
        "nunito-base-regular": "var(--nunito-base-regular-font-family)",
        "nunito-base-semibold": "var(--nunito-base-semibold-font-family)",
        "nunito-h6-bold": "var(--nunito-h6-bold-font-family)",
        "regular-11-px": "var(--regular-11-px-font-family)",
        "regular-13-px": "var(--regular-13-px-font-family)",
        "regular-15-px": "var(--regular-15-px-font-family)",
        "semibold-16-px": "var(--semibold-16-px-font-family)",
        "sora-h5-bold": "var(--sora-h5-bold-font-family)",
        "sora-h5-semibold": "var(--sora-h5-semibold-font-family)",
        "sora-h6-semibold": "var(--sora-h6-semibold-font-family)",
        "sora-large-semibold": "var(--sora-large-semibold-font-family)",
        "sora-small-bold": "var(--sora-small-bold-font-family)",
        "subhead-bold": "var(--subhead-bold-font-family)",
        "subhead-medium": "var(--subhead-medium-font-family)",
        "subhead-regular": "var(--subhead-regular-font-family)",
        "subheadline-subheadline-semibold":
          "var(--subheadline-subheadline-semibold-font-family)",
        "title-title-3-semibold": "var(--title-title-3-semibold-font-family)",
        "title2-bold": "var(--title2-bold-font-family)",
        "title3-bold": "var(--title3-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "bottom-3": "var(--bottom-3)",
        "bottom-4": "var(--bottom-4)",
        "card-shadow": "var(--card-shadow)",
        "white-BG": "var(--white-BG)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
